# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_id', models.IntegerField(blank=True, null=True)),
                ('bk_type', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Business'), ('2', 'Keyword')], max_length=10, null=True)),
                ('bk_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
